// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/config": {
            "get": {
                "description": "Returns deployment mode and authentication requirements.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get server configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ConfigResponseDto"
                        }
                    }
                }
            }
        },
        "/api/games": {
            "get": {
                "description": "Scans the games directory and returns manifests with metadata and tags.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "List discovered games",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.GameManifest"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/session": {
            "get": {
                "description": "Returns live status snapshot of the current streaming session.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Get current game session status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/session.SessionStatus"
                        }
                    }
                }
            }
        },
        "/api/session/start": {
            "post": {
                "description": "Starts a new game instance and its virtual display framebuffer.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Launch a game session",
                "parameters": [
                    {
                        "description": "Game launch configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.StartSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/session.SessionStatus"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/session/stop": {
            "post": {
                "description": "Safely stops the active game session and tears down virtual framebuffers.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Terminate the active game session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/session.SessionStatus"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "resource not found"
                }
            }
        },
        "domain.GameManifest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "The deepest, most intricate simulation of a world that's ever been created."
                },
                "engine": {
                    "type": "string",
                    "example": "sdl2-opengl"
                },
                "env": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "executable": {
                    "type": "string",
                    "example": "/game/dwarfort"
                },
                "id": {
                    "type": "string",
                    "example": "dwarf-fortress"
                },
                "name": {
                    "type": "string",
                    "example": "Dwarf Fortress"
                },
                "requiresXvfb": {
                    "type": "boolean",
                    "example": true
                },
                "saveDirs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "data/save"
                    ]
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Tag"
                    }
                },
                "workingDir": {
                    "type": "string",
                    "example": "/game"
                }
            }
        },
        "domain.Tag": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "string",
                    "enum": [
                        "genre",
                        "subgenre"
                    ],
                    "example": "genre"
                },
                "name": {
                    "type": "string",
                    "example": "Simulation"
                }
            }
        },
        "dto.ConfigResponseDto": {
            "type": "object",
            "properties": {
                "authRequired": {
                    "type": "boolean",
                    "example": false
                },
                "mode": {
                    "type": "string",
                    "example": "self-hosted"
                }
            }
        },
        "dto.StartSessionRequest": {
            "type": "object",
            "required": [
                "gameId"
            ],
            "properties": {
                "args": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[]"
                    ]
                },
                "gameId": {
                    "type": "string",
                    "example": "dwarf-fortress"
                }
            }
        },
        "session.SessionState": {
            "type": "string",
            "enum": [
                "idle",
                "starting",
                "running",
                "stopping"
            ],
            "x-enum-varnames": [
                "StateIdle",
                "StateStarting",
                "StateRunning",
                "StateStopping"
            ]
        },
        "session.SessionStatus": {
            "type": "object",
            "properties": {
                "gameId": {
                    "type": "string",
                    "example": "dwarf-fortress"
                },
                "gameName": {
                    "type": "string",
                    "example": "Dwarf Fortress"
                },
                "pid": {
                    "type": "integer",
                    "example": 104
                },
                "startedAt": {
                    "type": "string",
                    "example": "2026-09-25T02:00:00Z"
                },
                "state": {
                    "enum": [
                        "idle",
                        "starting",
                        "running",
                        "stopping"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/session.SessionState"
                        }
                    ],
                    "example": "running"
                },
                "uptimeSec": {
                    "type": "integer",
                    "example": 42
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8484",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Remote-DF Hub Server API",
	Description:      "Enterprise-grade self-hosted game streaming hub and process supervisor.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
