services:
  remote-df:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    container_name: remote-df
    ports:
      - "${PORT:-8484}:8484/tcp"
      - "${PORT:-8484}:8484/udp"
    volumes:
      - "${DF_DIR:-/tmp/df_install}:/game:z"
    restart: unless-stopped
